<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Tensors" data-toc-modified-id="Tensors-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Tensors</a></span></li><li><span><a href="#Random-Functions" data-toc-modified-id="Random-Functions-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Random Functions</a></span></li><li><span><a href="#Ones" data-toc-modified-id="Ones-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Ones</a></span></li><li><span><a href="#Addition" data-toc-modified-id="Addition-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Addition</a></span></li><li><span><a href="#Reshape" data-toc-modified-id="Reshape-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Reshape</a></span></li><li><span><a href="#From/to-numpy" data-toc-modified-id="From/to-numpy-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>From/to numpy</a></span></li><li><span><a href="#Matrix-Multiplication" data-toc-modified-id="Matrix-Multiplication-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Matrix Multiplication</a></span></li></ul></div>

In [2]:
import tensorflow as tf
import torch
import numpy as np

## Tensors

It turns out neural network computations are just a bunch of linear algebra operations on *tensors*, a generalization of matrices. A vector is a 1-dimensional tensor, a matrix is a 2-dimensional tensor, an array with three indices is a 3-dimensional tensor (RGB color images for example). The fundamental data structure for neural networks are tensors and PyTorch (as well as pretty much every other deep learning framework) is built around tensors.

<img src="assets/tensor_examples.svg" width=600px>

With the basics covered, it's time to explore how we can use PyTorch to build a simple neural network.

## Random Functions

In [3]:
x_tf = tf.random.uniform([3,2])
x_pt = torch.rand(3,2)
x_np = np.random.uniform(size=(3,2))

x_tf, x_pt, x_np

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.15498841, 0.9426929 ],
        [0.20825231, 0.6376492 ],
        [0.92591393, 0.4118954 ]], dtype=float32)>,
 tensor([[0.4391, 0.0434],
         [0.0618, 0.1094],
         [0.7931, 0.3834]]),
 array([[0.09619363, 0.72100511],
        [0.11518072, 0.99289554],
        [0.16197249, 0.87337089]]))

## Ones

In [4]:
ones_tf = tf.ones(x_tf.shape)
ones_pt = torch.ones(x_pt.size()) #shape also works
ones_np = np.ones(x_np.shape)

ones_tf, ones_pt, ones_np

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

## Addition

In [5]:
z_tf = x_tf + ones_tf
z_pt = x_pt + ones_pt
z_np = x_np + ones_np

z_tf, z_pt, z_np

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1.1549884, 1.9426929],
        [1.2082523, 1.6376492],
        [1.9259139, 1.4118954]], dtype=float32)>,
 tensor([[1.4391, 1.0434],
         [1.0618, 1.1094],
         [1.7931, 1.3834]]),
 array([[1.09619363, 1.72100511],
        [1.11518072, 1.99289554],
        [1.16197249, 1.87337089]]))

In [6]:
z_tf[0], z_pt[0], z_np[0]

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1549884, 1.9426929], dtype=float32)>,
 tensor([1.4391, 1.0434]),
 array([1.09619363, 1.72100511]))

In [7]:
z_tf + 1, z_pt + 1, z_np + 1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[2.1549883, 2.9426928],
        [2.2082524, 2.637649 ],
        [2.9259138, 2.4118953]], dtype=float32)>,
 tensor([[2.4391, 2.0434],
         [2.0618, 2.1094],
         [2.7931, 2.3834]]),
 array([[2.09619363, 2.72100511],
        [2.11518072, 2.99289554],
        [2.16197249, 2.87337089]]))

In [8]:
z_pt.add_(1) # Works in-place

tensor([[2.4391, 2.0434],
        [2.0618, 2.1094],
        [2.7931, 2.3834]])

## Reshape

In [9]:
new_shape = (2,3)
tf.reshape(z_tf,new_shape), z_pt.reshape(new_shape), z_np.reshape(new_shape)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1.1549884, 1.9426929, 1.2082523],
        [1.6376492, 1.9259139, 1.4118954]], dtype=float32)>,
 tensor([[2.4391, 2.0434, 2.0618],
         [2.1094, 2.7931, 2.3834]]),
 array([[1.09619363, 1.72100511, 1.11518072],
        [1.99289554, 1.16197249, 1.87337089]]))

Reshaping tensors is a really common operation. First to get the size and shape of a tensor use `.size()`. Then, to reshape a tensor, use `.resize_()`. Notice the underscore, reshaping is an in-place operation.

In [10]:
z_pt.resize_(new_shape)

tensor([[2.4391, 2.0434, 2.0618],
        [2.1094, 2.7931, 2.3834]])

In [11]:
z_pt

tensor([[2.4391, 2.0434, 2.0618],
        [2.1094, 2.7931, 2.3834]])

## From/to numpy

In [16]:
b_tf = tf.Variable(z_np)
b_tf_dataset = tf.data.Dataset.from_tensor_slices(z_np)
b_pt = torch.from_numpy(z_np)

b_tf, b_tf_dataset, b_pt

(<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
 array([[1.09619363, 1.72100511],
        [1.11518072, 1.99289554],
        [1.16197249, 1.87337089]])>,
 <TensorSliceDataset shapes: (2,), types: tf.float64>,
 tensor([[1.0962, 1.7210],
         [1.1152, 1.9929],
         [1.1620, 1.8734]], dtype=torch.float64))

In [34]:
torch.as_tensor(z_np) # Avoids copy from numpy array

tensor([[1.0962, 1.7210],
        [1.1152, 1.9929],
        [1.1620, 1.8734]], dtype=torch.float64)

In [35]:
torch.tensor(z_np) # Copies numpy array

tensor([[1.0962, 1.7210],
        [1.1152, 1.9929],
        [1.1620, 1.8734]], dtype=torch.float64)

In [21]:
for x in b_tf_dataset.take(3):
    print(x)

tf.Tensor([1.09619363 1.72100511], shape=(2,), dtype=float64)
tf.Tensor([1.11518072 1.99289554], shape=(2,), dtype=float64)
tf.Tensor([1.16197249 1.87337089], shape=(2,), dtype=float64)


In [23]:
b_tf.numpy(), b_pt.numpy()

(array([[1.09619363, 1.72100511],
        [1.11518072, 1.99289554],
        [1.16197249, 1.87337089]]),
 array([[1.09619363, 1.72100511],
        [1.11518072, 1.99289554],
        [1.16197249, 1.87337089]]))

## Matrix Multiplication

In [26]:
tf.matmul(b_tf, b_tf, transpose_a=True)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 3.79544855,  6.28579894],
       [ 6.28579894, 10.44300973]])>

In [28]:
torch.matmul(b_pt.T,b_pt)

tensor([[ 3.7954,  6.2858],
        [ 6.2858, 10.4430]], dtype=torch.float64)

In [31]:
tf.linalg.matrix_transpose(b_tf) @ b_tf

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 3.79544855,  6.28579894],
       [ 6.28579894, 10.44300973]])>

In [32]:
b_pt.T @ b_pt

tensor([[ 3.7954,  6.2858],
        [ 6.2858, 10.4430]], dtype=torch.float64)

In [33]:
z_np.T @ z_np

array([[ 3.79544855,  6.28579894],
       [ 6.28579894, 10.44300973]])